print("Ola!\nQual o teu nome?")
nome= input()
print("Qual a sua Cidade?")
cidade= input()
print("Qual o nome do teu animal de estimação?")
pet= input()
print(nome+" nasceu na cidade de " + cidade+" e possui o " +pet)